### ISSUE TITLE
test: fix failing CNS test due to bad API key in unstoppable package

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#561]
Currently in the umbra-js directory there is this failure when running `yarn test`

```
1) СNS functions
       gets the public keys associated with a CNS address:
     ResolutionError: < Request to https://polygon-mainnet.g.alchemy.com/v2/iG-oHZ2FvjqC9D43O5q9sj62out5ubsy failed with response status 401 >
      at new ResolutionError (/Users/mds/Documents/projects/umbra-protocol/node_modules/@unstoppabledomains/resolution/build/errors/resolutionError.js:99:24)
      at FetchProvider.<anonymous> (/Users/mds/Documents/projects/umbra-protocol/node_modules/@unstoppabledomains/resolution/build/FetchProvider.js:114:35)
      at step (/Users/mds/Documents/projects/umbra-protocol/node_modules/@unstoppabledomains/resolution/build/FetchProvider.js:56:23)
      at Object.next (/Users/mds/Documents/projects/umbra-protocol/node_modules/@unstoppabledomains/resolution/build/FetchProvider.js:37:53)
      at fulfilled (/Users/mds/Documents/projects/umbra-protocol/node_modules/@unstoppabledomains/resolution/build/FetchProvider.js:28:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Using ripgrep we can see that URL comes from the unstoppable package:

```sh
$ rg iG-oHZ2FvjqC9D43O5q9sj62out5ubsy --no-ignore
node_modules/@unstoppabledomains/resolution/build/UnsInternal.js
323:        'polygon-mainnet': 'https://polygon-mainnet.g.alchemy.com/v2/iG-oHZ2FvjqC9D43O5q9sj62out5ubsy',
```

in that `node_modules/@unstoppabledomains/resolution/build/UnsInternal.js` file we see:

```
UnsInternal.UrlMap = {
    mainnet: 'https://eth-mainnet.alchemyapi.io/v2/GmQ8X1FHf-WDEry0BBSn0RgjVhjHkRmS',
    rinkeby: 'https://eth-rinkeby.alchemyapi.io/v2/ZDERxOLIj120dh2-Io2Q9RTh9RfWEssT',
    goerli: 'https://eth-goerli.alchemyapi.io/v2/J-ff_OlmWzw41ocqwpkRccHdfqSZML4q',
    'polygon-mainnet': 'https://polygon-mainnet.g.alchemy.com/v2/iG-oHZ2FvjqC9D43O5q9sj62out5ubsy',
    'polygon-mumbai': 'https://polygon-mumbai.g.alchemy.com/v2/YtQwLH1UOmRGgQp_Rg1TXvFWSWeV5Y02',
};
```

Maybe we need to update the unstoppable package to a newer version which fixes this, if that's not the solution then we probably need to open an issue upstream for them to fix the key.

But I did confirm that replacing the `iG-oHZ2FvjqC9D43O5q9sj62out5ubsy` API key in that file with my own causes the tests to pass

**Comment by alexkeating** [comment]
Going to try updating the package on to see if that fixes the issue
