### ISSUE TITLE
Running `yarn test` in the contracts directory breaks `yarn test` at the repo level

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#71]
After running `yarn install` and `yarn test` at the top level, everything works.

Then, moving to the `contracts` subdir and running `yarn test`, everything continues to work.

Moving back out to the top level directory and running `yarn test` results in the following error:

```
@umbra/contracts: /Users/bendi/Development/umbra/node_modules/scrypt-shim/src/index.js:27
@umbra/contracts:       throw e;
@umbra/contracts:       ^
@umbra/contracts: Error: The module '/Users/bendi/Development/umbra/node_modules/scrypt/build/Release/scrypt.node'
@umbra/contracts: was compiled against a different Node.js version using
@umbra/contracts: NODE_MODULE_VERSION 64. This version of Node.js requires
@umbra/contracts: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
@umbra/contracts: the module (for instance, using `npm rebuild` or `npm install`).
@umbra/contracts:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
@umbra/contracts:     at Module.load (internal/modules/cjs/loader.js:879:32)
@umbra/contracts:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
@umbra/contracts:     at Module.require (internal/modules/cjs/loader.js:903:19)
@umbra/contracts:     at require (internal/modules/cjs/helpers.js:74:18)
@umbra/contracts:     at Object.<anonymous> (/Users/bendi/Development/umbra/node_modules/scrypt/index.js:3:20)
@umbra/contracts:     at Module._compile (internal/modules/cjs/loader.js:1015:30)
@umbra/contracts:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
@umbra/contracts:     at Module.load (internal/modules/cjs/loader.js:879:32)
@umbra/contracts:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
@umbra/contracts: error Command failed with exit code 1.
```

Is it possible we need a volta specification in the subdirs to ensure the same node version is used when running components separately? Just a guess based on the error message!

**Comment by wildmolasses** [comment]
Can't reproduce! can you try `rm -rf node_modules` (from root dir and also from /contracts), and then retrying the steps from above?

**Comment by apbendi** [comment]
Seems to be resolved, thanks @wildmolasses
